name: 'Run Integration Tests'
description: 'This action runs integration tests from the outputs of a given workflow run'
inputs:
  target-run-id:
    description: 'The github run id whose artifacts will be tested. Defaults to github.event.workflow_run.id'
    required: false
  gcp-token:
    description: 'Google Cloud Platform service account token (in json)'
    required: true
  github-token:
    description: 'Github token that will be used to access github APIs to fetch artifacts'
    required: true
  output-folder:
    description: 'The output folder to download results into'
    required: true
runs:
  using: "composite"
  steps:
    # dist.yml will parse the marker below and replace the next line
    - run: ${{ github.action_path }}/dist/bin/cli
      shell: bash
      env:
        ANDROIDX_GITHUB_TOKEN: ${{ inputs.github-token }}
        ANDROIDX_GCLOUD_CREDENTIALS: ${{ inputs.gcp-token }}
        ANDROIDX_TARGET_RUN_ID: ${{ github.event.workflow_run.id || inputs.target-run-id }}
        ANDROIDX_HOST_RUN_ID: ${{ github.run_id }}
        ANDROIDX_OUTPUT_FOLDER: ${{ inputs.output-folder }}
