name: 'Run Integration Tests'
description: 'This action runs integration tests from the outputs of a given workflow run'
inputs:
  target-run-id:
    description: 'The github run id whose artifacts will be tested. Defaults to github.event.workflow_run.id'
    required: false
  gcp-token:
    description: 'Google Cloud Platform service account token (in json)'
    required: true
  github-token:
    description: 'Github token that will be used to access github APIs to fetch artifacts'
    required: true
  output-folder:
    description: 'The output folder to download results into'
    required: true
  device-specs:
    description: |
      Specs for devices. e.g. redfin:30, sailfish:25.
      If not set, an API compatible device will be picked.
      See https://firebase.google.com/docs/test-lab/android/available-testing-devices
      for list of available devices.
    required: false
  log-file:
    description: 'Log file to export test runner logs.'
    required: false
  artifact-name-filter-regex:
    description: 'A regex (kotlin) to filter artifact names when looking for APKs.'
    required: false
  gcp-bucket-name:
    description: 'The name of the GCP Cloud Storage bucket that will be used to keep artifacts and results'
    required: true
  gcp-bucket-path:
    description: 'The folder to use inside the bucket'
    required: true
  use-test-config-files:
    description: 'An internal flag for androidx/androidx to use test config files in artifacts for selecting which tests to run'
    required: false

runs:
  using: "composite"
  steps:
    # dist.yml will parse the marker below and replace the next line
    #REPLACE_NEXT_LINE- run: ${{ github.action_path }}/dist/bin/cli
    - run: cd ${{ github.action_path }}/AndroidXCI && ./gradlew :cli:run
      shell: bash
      env:
        ANDROIDX_GITHUB_TOKEN: ${{ inputs.github-token }}
        ANDROIDX_GCLOUD_CREDENTIALS: ${{ inputs.gcp-token }}
        ANDROIDX_TARGET_RUN_ID: ${{ github.event.workflow_run.id || inputs.target-run-id }}
        ANDROIDX_HOST_RUN_ID: ${{ github.run_id }}
        ANDROIDX_OUTPUT_FOLDER: ${{ inputs.output-folder }}
        ANDROIDX_DEVICE_SPECS: ${{ inputs.device-specs }}
        ANDROIDX_LOG_FILE: ${{ inputs.log-file }}
        ANDROIDX_ARTIFACT_NAME_FILTER_REGEX: ${{ inputs.artifact-name-filter-regex }}
        ANDROIDX_BUCKET_NAME: ${{ inputs.gcp-bucket-name }}
        ANDROIDX_BUCKET_PATH: ${{ inputs.gcp-bucket-path }}
        ANDROIDX_USE_TEST_CONFIG_FILES: ${{ inputs.use-test-config-files }}