name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: eskatos/gradle-command-action@v1
        with: 
          build-root-directory: AndroidXCI
          wrapper-directory: AndroidXCI
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: check :ftlModelBuilder:check
      - name: "Upload build repository"
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: repo
          path: ${{ env.GITHUB_WORKSPACE }}/AndroidXCI/build/repo