# when `latest` tag or another tag starting with `v` is pushed,
# this workflow runs to push the distrubtion into a `dist-<tag>`
# tag
name: DISTRIBUTE

on:
  push:
    tags:
      - latest
      - v*

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "checkout"
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # always test before dist
      - uses: eskatos/gradle-command-action@v1
        name: Build and Test
        with: 
          build-root-directory: AndroidXCI
          wrapper-directory: AndroidXCI
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: check :ftlModelBuilder:check
      # build distribution
      - uses: eskatos/gradle-command-action@v1
        name: Build Distribution
        with: 
          build-root-directory: AndroidXCI
          wrapper-directory: AndroidXCI
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: :cli:installDist
      # push it to a new git tag
      - name: "create dist branch"
        id: event-args
        run: |
          set -x
          REF="${{ github.event.ref }}"
          TAG=$(echo $REF| sed 's/refs\/tags\///')
          DIST_TAG="dist-$TAG"
          git config user.email "${{ github.event.head_commit.author.email }}"
          git config user.name "${{ github.event.head_commit.author.name }}"
          git checkout -b tmp-$DIST_TAG
          # remove workflow etc, otherwise we'll need workflow override permissions
          rm -rf .github
          git add .github

          # replace src build command with dist
          REPLACE_TOKEN="#REPLACE_NEXT_LINE"
          sed -i "/$REPLACE_TOKEN/{n;d}" action.yml
          sed -i "s/$REPLACE_TOKEN//g" action.yml
          git add action.yml

          # copy install into dist folder
          cp -R AndroidXCI/cli/build/install/cli dist
          # add the dist folder
          git add dist
          git commit -m "distrubtion for $TAG in $DIST_TAG branch"
          git tag -a $DIST_TAG -m "dist for $TAG" -f
          git push origin $DIST_TAG -f
          echo "done pushing to git"
