# when `latest` tag or another tag starting with `v` is pushed,
# this workflow runs to push the distrubtion into a `dist-<tag>`
# tag
name: DISTRIBUTE

on:
  push:
    tags:
      - latest
      - v*
jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "checkout"
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2
        with:
          # Don't reuse cache entries from any other Job.
          gradle-home-cache-strict-match: true

          # Limit the size of the cache entry.
          # These directories contain instrumented/transformed dependency jars which can be reconstructed relatively quickly.
          gradle-home-cache-excludes: |
            caches/jars-9
            caches/transforms-3
      # always test before dist
      - name: "Build and Test"
        working-directory: AndroidXCI
        shell: bash
        run: ./gradlew check :ftlModelBuilder:check  --no-configuration-cache
      - name: "Distribute"
        working-directory: AndroidXCI
        shell: bash
        run: ./gradlew :cli:installDist --no-configuration-cache
      # push it to a new git tag
      - name: "create dist branch"
        id: event-args
        env:
          GIT_EMAIL: ${{ github.event.head_commit.author.email }}
          GIT_AUTHOR: ${{ github.event.head_commit.author.name }}
        run: |
          set -x
          REF="${{ github.event.ref }}"
          TAG=$(echo $REF| sed 's/refs\/tags\///')
          DIST_TAG="dist-$TAG"
          git config user.email "$GIT_EMAIL"
          git config user.name "$GIT_AUTHOR"
          git checkout -b tmp-$DIST_TAG
          # remove workflow etc, otherwise we'll need workflow override permissions
          rm -rf .github
          git add .github

          # replace src build command with dist
          REPLACE_TOKEN="#REPLACE_NEXT_LINE"
          sed -i "/$REPLACE_TOKEN/{n;d}" action.yml
          sed -i "s/$REPLACE_TOKEN//g" action.yml
          git add action.yml

          # copy install into dist folder
          cp -R AndroidXCI/cli/build/install/cli dist
          # add the dist folder
          git add dist
          git commit -m "distrubtion for $TAG in $DIST_TAG branch"
          git tag -a $DIST_TAG -m "dist for $TAG" -f
          git push origin $DIST_TAG -f
          echo "done pushing to git"
